export const we_data = {
  "response": {
    "version": "0.1",
    "termsofService": "http://www.wunderground.com/weather/api/d/terms.html",
    "features": {
      "conditions": 1
    }
  },
  "current_observation": {
    "image": {
      "url": "http://icons.wxug.com/graphics/wu2/logo_130x80.png",
      "title": "Weather Underground",
      "link": "http://www.wunderground.com"
    },
    "display_location": {
      "full": "London, United Kingdom",
      "city": "London",
      "state": "GLA",
      "state_name": "United Kingdom",
      "country": "UK",
      "country_iso3166": "GB",
      "zip": "00000",
      "magic": "1",
      "wmo": "03772",
      "latitude": "51.47999954",
      "longitude": "-0.44999999",
      "elevation": "24.1"
    },
    "observation_location": {
      "full": "London, ",
      "city": "London",
      "state": "",
      "country": "GB",
      "country_iso3166": "GB",
      "latitude": "51.47999954",
      "longitude": "-0.44999999",
      "elevation": "79 ft"
    },
    "estimated": {},
    "station_id": "EGLL",
    "observation_time": "Last Updated on March 2, 8:50 PM GMT",
    "observation_time_rfc822": "Thu, 02 Mar 2017 20:50:00 +0000",
    "observation_epoch": "1488487800",
    "local_time_rfc822": "Thu, 02 Mar 2017 21:19:02 +0000",
    "local_epoch": "1488489542",
    "local_tz_short": "GMT",
    "local_tz_long": "Europe/London",
    "local_tz_offset": "+0000",
    "weather": "Clear",
    "temperature_string": "45 F (7 C)",
    "temp_f": 45,
    "temp_c": 7,
    "relative_humidity": "81%",
    "wind_string": "From the South at 9 MPH",
    "wind_dir": "South",
    "wind_degrees": 180,
    "wind_mph": 9,
    "wind_gust_mph": 0,
    "wind_kph": 15,
    "wind_gust_kph": 0,
    "pressure_mb": "1012",
    "pressure_in": "29.89",
    "pressure_trend": "0",
    "dewpoint_string": "39 F (4 C)",
    "dewpoint_f": 39,
    "dewpoint_c": 4,
    "heat_index_string": "NA",
    "heat_index_f": "NA",
    "heat_index_c": "NA",
    "windchill_string": "40 F (4 C)",
    "windchill_f": "40",
    "windchill_c": "4",
    "feelslike_string": "40 F (4 C)",
    "feelslike_f": "40",
    "feelslike_c": "4",
    "visibility_mi": "6.2",
    "visibility_km": "10.0",
    "solarradiation": "--",
    "UV": "-1",
    "precip_1hr_string": "-9999.00 in (-9999.00 mm)",
    "precip_1hr_in": "-9999.00",
    "precip_1hr_metric": "--",
    "precip_today_string": "0.00 in (0.0 mm)",
    "precip_today_in": "0.00",
    "precip_today_metric": "0.0",
    "icon": "clear",
    "icon_url": "http://icons.wxug.com/i/c/k/nt_clear.gif",
    "forecast_url": "http://www.wunderground.com/global/stations/03772.html",
    "history_url": "http://www.wunderground.com/history/airport/EGLL/2017/3/2/DailyHistory.html",
    "ob_url": "http://www.wunderground.com/cgi-bin/findweather/getForecast?query=51.47999954,-0.44999999",
    "nowcast": ""
  }
}